# hugo server --themesDir ...

baseURL: https://developweekly.com
title: developweekly
theme: hugo-book

# for syntax highlighting
pygmentsCodeFences: true

# Book configuration
disablePathToLower: true

params:
  # show or hide table of contents for page
  BookShowToC: true

  # Set bundle to render side menu
  # if not specified file structure and weights will be used
  BookMenuBundle: /menu

  # specify section of content to render as menu
  # if bookMenuBundle is not set, 'docs' is value by default
  BookSection: docs

markup:
  goldmark:
    renderer:
      unsafe: true
